name: CI Build ZIPRAF OMEGA FULL

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "CI Build: Compilar APK quântico ORIGINUM :: PULSE"
